Repository CHA-CALL/ChaCall-FE, pull requests merged in 2025-09, with the labels that each got.

#10 [Init/#3] eslint prettier setting
  .prettierignore
  .prettierrc
  App.tsx
  eslint.config.js
  index.html
  main.tsx
  package.json
  pnpm-lock.yaml
  src/router/constant/routes.ts
  src/router/router.tsx
Labels: 🎉 Init, 🦁 찬영

#7 [Init/#6] global style
  index.css
  index.html
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/App.tsx
  src/main.tsx
  src/pages/home/Home.tsx
  src/router/router.tsx
  src/shared/styles/global.css
  src/shared/styles/reset.css
  src/shared/styles/sharedStyles.css
  src/shared/utils/cn.tsx
Labels: 🎉 Init, 🦊 동희

#24 [Feature/#20] icon component
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/svg/.gitkeep
  src/assets/svg/SvgSprite.tsx
  src/assets/svg/ic_sprite.svg
  src/assets/svg/index.ts
  src/pages/home/Home.tsx
  src/shared/components/icon/Icon.stories.tsx
  src/shared/components/icon/Icon.tsx
  vite-env.d.ts
  vite.config.ts
Labels: ✨Feature, 🦁 찬영

#23 [Feature] layout 설정
  src/pages/home/Home.tsx
  src/router/Layout.tsx
  src/router/router.tsx
  src/shared/styles/reset.css
  src/shared/styles/sharedStyles.css
Labels: ✨Feature, 🦊 동희

#17 [Feature/#16] button 컴포넌트
  src/shared/components/button/Button.stories.tsx
  src/shared/components/button/Button.tsx
Labels: ✨Feature, 🦊 동희

#22 [Feature/#18] 네비게이션 컴포넌트
  .storybook/preview.ts
  src/shared/components/icon/Icon.stories.tsx
  src/shared/components/navigation/Navigation.stories.tsx
  src/shared/components/navigation/Navigation.tsx
Labels: ✨Feature, 🦊 동희

#33 [Feature/#19] search bar
  package.json
  pnpm-lock.yaml
  src/router/router.tsx
  src/shared/components/searchBar/SearchBar.stories.tsx
  src/shared/components/searchBar/SearchBar.tsx
  src/shared/styles/reset.css
  src/shared/styles/sharedStyles.css
Labels: ✨Feature, 🦊 동희

#43 [Feature/#40]: 공통 컴포넌트 Tag
  src/shared/components/tag/Tag.stories.tsx
  src/shared/components/tag/Tag.tsx
Labels: ✨Feature, 🐯 동윤

#44 [Feature/#25] button tab component
  src/shared/components/button-tab/ButtonTab.stories.tsx
  src/shared/components/button-tab/ButtonTab.tsx
  src/shared/components/button-tab/ButtonTabGroup.tsx
Labels: ✨Feature, 🐣 정현

#47 [Feature/#28] close button component
  src/assets/svg/ic_sprite.svg
  src/shared/components/button-close/ButtonClose.stories.tsx
  src/shared/components/button-close/ButtonClose.tsx
  src/shared/components/icon/Icon.stories.tsx
  src/shared/components/icon/Icon.tsx
Labels: ✨Feature, 🐣 정현

#48 [Feature/#29] button trash component
  src/shared/components/button-trash/ButtonTrash.stories.tsx
  src/shared/components/button-trash/ButtonTrash.tsx
Labels: ✨Feature, 🐣 정현

#50 [Feature/#30] modal component
  src/shared/components/modal/Modal.stories.tsx
  src/shared/components/modal/Modal.tsx
Labels: ✨Feature, 🐣 정현

#37 [Feature/#34] select chip
  src/shared/components/select-chip/SelectChip.stories.tsx
  src/shared/components/select-chip/SelectChip.tsx
Labels: ✨Feature, 🐯 동윤

#53 [Feature/#41] chat list item 컴포넌트 구현, Tag, CheckButton 컴포넌트 일부 수정
  src/pages/home/Home.tsx
  src/shared/components/button-check/ButtonCheck.stories.tsx
  src/shared/components/button-check/ButtonCheck.tsx
  src/shared/components/chat-list-item/ChatListItem.stories.tsx
  src/shared/components/chat-list-item/ChatListItem.tsx
  src/shared/components/tag/Tag.tsx
Labels: ✨Feature, 🐯 동윤

#54 [Feature/#35] calendar component
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/assets/svg/ic_sprite.svg
  src/pages/home/Home.tsx
  src/shared/components/bottom-sheet/BottomSheet.stories.tsx
  src/shared/components/bottom-sheet/BottomSheet.tsx
  src/shared/components/button-date/ButtonDate.stories.tsx
  src/shared/components/button-date/ButtonDate.tsx
  src/shared/components/button/Button.tsx
  src/shared/components/calendar/Calendar.stories.tsx
  src/shared/components/calendar/Calendar.tsx
  src/shared/components/calendar/components/CalendarDayButton.tsx
  src/shared/components/calendar/components/CalendarSelectedCircle.tsx
  src/shared/components/calendar/hooks/use-calendar-days.ts
  src/shared/components/calendar/utils/calendar-utils.ts
  src/shared/components/icon/Icon.stories.tsx
  src/shared/components/icon/Icon.tsx
  src/shared/hooks/.gitkeep
  src/shared/hooks/use-bottom-sheet-drag.ts
  src/shared/styles/reset.css
  src/shared/types/calendar-types.ts
  src/shared/utils/date-formatter.ts
Labels: ✨Feature, 🦁 찬영

#64 [Feature] owner onboarding
  package.json
  pnpm-lock.yaml
  src/assets/svg/ic_sprite.svg
  src/pages/owner-onboarding/FoodTruckOnboarding.tsx
  src/pages/owner-onboarding/components/BizRegCertSection.tsx
  src/pages/owner-onboarding/components/NameSection.tsx
  src/pages/owner-onboarding/components/OtherDocsSection.tsx
  src/pages/owner-onboarding/components/SectionTitle.tsx
  src/pages/owner-onboarding/constants/owner.ts
  src/pages/owner-onboarding/hooks/useFileUpload.tsx
  src/pages/owner-onboarding/hooks/useFoodTruckInput.tsx
  src/pages/owner-onboarding/hooks/useFoodTruckName.tsx
  src/router/constant/routes.ts
  src/router/router.tsx
  src/shared/components/button-add-image/ButtonAddImage.tsx
  src/shared/components/error-text/ErrorText.stories.tsx
  src/shared/components/error-text/ErrorText.tsx
  src/shared/components/icon/Icon.tsx
  src/shared/components/image-preview/ImagePreview.tsx
  src/shared/components/search-bar/SearchBar.tsx
  src/shared/constant/image.ts
  src/shared/utils/image.ts
Labels: ✨Feature, 🦊 동희

#75 [Chore/#74] tailwind class 자동 정렬
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/pages/filter/Filter.tsx
  src/pages/home/Home.tsx
  src/pages/owner-onboarding/FoodTruckOnboarding.tsx
  src/pages/owner-onboarding/components/OtherDocsSection.tsx
  src/pages/owner-onboarding/components/SectionTitle.tsx
  src/pages/owner-onboarding/hooks/useFileUpload.ts
  src/pages/owner-onboarding/hooks/useFoodTruckInput.ts
  src/pages/owner-onboarding/hooks/useFoodTruckName.ts
  src/router/Layout.tsx
  src/shared/components/button-add-image/ButtonAddImage.tsx
  src/shared/components/button-date/ButtonDate.tsx
  src/shared/components/button-tab/ButtonTab.tsx
  src/shared/components/button-trash/ButtonTrash.tsx
  src/shared/components/chat-list-item/ChatListItem.tsx
  src/shared/components/custom-toast/CustomToast.tsx
  src/shared/components/error-text/ErrorText.tsx
  src/shared/components/image-preview/ImagePreview.tsx
  src/shared/components/modal/Modal.tsx
  src/shared/components/navigation/Navigation.tsx
  src/shared/components/search-bar/SearchBar.tsx
  src/shared/components/select-chip/SelectChip.tsx
  src/shared/components/tag/Tag.tsx
  src/shared/components/tooltip/Tooltip.tsx
  src/shared/utils/cn.tsx
Labels: 🛠️ Setting, 🦁 찬영

#78 [Fix/#77] modify modal component
  src/shared/components/modal/Modal.tsx
Labels: 🎨 Style, 🔨 Fix, 🐣 정현

#73 [Feature/#63] set location page
  src/pages/set-location/SetLocation.tsx
  src/pages/set-location/components/DongEupMeonItem.tsx
  src/pages/set-location/components/LocationCategoryLabels.tsx
  src/pages/set-location/components/SearchResultItem.tsx
  src/pages/set-location/components/SelectedChipsSheet.tsx
  src/pages/set-location/components/SiDoItem.tsx
  src/pages/set-location/components/SiGunGuItem.tsx
  src/pages/set-location/constant/mocks.ts
  src/pages/set-location/constant/set-location.ts
  src/pages/set-location/hooks/use-locations.ts
  src/router/constant/routes.ts
  src/router/router.tsx
Labels: ✨Feature, 🐯 동윤

#80 [Refactor/#79] refactor components
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/workflows/ci.yml
  .prettierrc
  eslint.config.js
  postcss.config.js
  src/pages/chat-list/ChatList.tsx
  src/pages/chat-list/components/ChatListManageBar.tsx
  src/pages/filter/Filter.tsx
  src/pages/filter/components/FilterChipGroup.tsx
  src/pages/home/Home.tsx
  src/pages/owner-onboarding/FoodTruckOnboarding.tsx
  src/pages/owner-onboarding/components/OtherDocsSection.tsx
  src/pages/owner-onboarding/components/SectionTitle.tsx
  src/pages/reservation/Reservation.tsx
  src/pages/reservation/components/FoodTruckItem.tsx
  src/shared/components/bottom-sheet/BottomSheet.tsx
  src/shared/components/button-add-image/ButtonAddImage.tsx
  src/shared/components/button-check/ButtonCheck.tsx
  src/shared/components/button-date/ButtonDate.tsx
  src/shared/components/button-floating/ButtonFloating.tsx
  src/shared/components/button-icon/ButtonIcon.stories.tsx
  src/shared/components/button-icon/ButtonIcon.tsx
  src/shared/components/button-tab/ButtonTab.tsx
  src/shared/components/button-tab/ButtonTabGroup.tsx
  src/shared/components/button-text/ButtonText.tsx
  src/shared/components/button-trash/ButtonTrash.tsx
  src/shared/components/button/Button.tsx
  src/shared/components/calendar/Calendar.stories.tsx
  src/shared/components/calendar/Calendar.tsx
  src/shared/components/calendar/components/CalendarDayButton.tsx
  src/shared/components/calendar/components/CalendarSelectedCircle.tsx
  src/shared/components/calendar/utils/calendar-utils.ts
  src/shared/components/chat-list-item/ChatListItem.tsx
  src/shared/components/custom-toast/CustomToast.stories.tsx
  src/shared/components/custom-toast/CustomToast.tsx
  src/shared/components/error-text/ErrorText.stories.tsx
  src/shared/components/error-text/ErrorText.tsx
  src/shared/components/image-preview/ImagePreview.stories.tsx
  src/shared/components/image-preview/ImagePreview.tsx
  src/shared/components/modal/Modal.stories.tsx
  src/shared/components/modal/Modal.tsx
  src/shared/components/overlay/Overlay.stories.tsx
  src/shared/components/overlay/Overlay.tsx
  src/shared/components/search-bar/SearchBar.tsx
  src/shared/components/select-chip/SelectChip.stories.tsx
  src/shared/components/select-chip/SelectChip.tsx
  src/shared/components/tag/Tag.stories.tsx
  src/shared/components/tag/Tag.tsx
  src/shared/components/tooltip/Tooltip.stories.tsx
  src/shared/components/tooltip/Tooltip.tsx
  vitest.shims.d.ts
Labels: 🌈 Refactor, 🦊 동희

#88 [Style/#85] Overlay 및 전체 레이아웃 관련 수정
  src/pages/filter/Filter.tsx
  src/pages/home/Home.tsx
  src/shared/components/overlay/Overlay.tsx
  src/shared/styles/sharedStyles.css
Labels: 🎨 Style, 🦁 찬영

#93 [Init/#76] swagger typescript api 세팅
  apis/Auth.ts
  apis/Members.ts
  apis/Owners.ts
  apis/Regions.ts
  apis/Reservations.ts
  apis/Users.ts
  apis/data-contracts.ts
  apis/http-client.ts
  package.json
  pnpm-lock.yaml
  src/pages/filter/Filter.tsx
  src/pages/home/Home.tsx
  src/shared/components/bottom-sheet/BottomSheet.tsx
Labels: 🎉 Init, 🦊 동희, 🦁 찬영

#86 [Feature/#84] message list page
  src/assets/svg/ic_sprite.svg
  src/pages/@owner/food-truck-onboarding/FoodTruckOnboarding.tsx
  src/pages/@owner/food-truck-onboarding/components/BizRegCertSection.tsx
  src/pages/@owner/food-truck-onboarding/components/NameSection.tsx
  src/pages/@owner/food-truck-onboarding/components/OtherDocsSection.tsx
  src/pages/@owner/food-truck-onboarding/components/SectionTitle.tsx
  src/pages/@owner/food-truck-onboarding/constants/owner.ts
  src/pages/@owner/food-truck-onboarding/hooks/useFileUpload.ts
  src/pages/@owner/food-truck-onboarding/hooks/useFoodTruckInput.ts
  src/pages/@owner/food-truck-onboarding/hooks/useFoodTruckName.ts
  src/pages/@owner/message-list/@modal/(.)confirm-modal/ConfirmModal.tsx
  src/pages/@owner/message-list/MessageList.tsx
  src/pages/@owner/message-list/components/Message.tsx
  src/pages/@owner/message-list/components/MessageForm.tsx
  src/pages/@owner/message-list/mockup.ts
  src/router/constant/routes.ts
  src/router/router.tsx
  src/shared/components/button/Button.tsx
  src/shared/components/error-text/ErrorText.stories.tsx
  src/shared/components/icon/Icon.tsx
  src/shared/components/information/Information.stories.tsx
  src/shared/components/information/Information.tsx
  src/shared/components/navigation/Navigation.tsx
  src/shared/components/overlay/Overlay.stories.tsx
  src/shared/styles/reset.css
Labels: ✨Feature, 🦊 동희

#90 [Feature/#87] account page
  src/pages/@owner/account/@modal/(.)confirm-exit-modal/ConfirmExitModal.tsx
  src/pages/@owner/account/@modal/(.)save-account-modal/SaveAccountModal.tsx
  src/pages/@owner/account/@modal/(.)select-bank-bottom-sheet/SelectBankBottomSheet.tsx
  src/pages/@owner/account/Account.tsx
  src/pages/@owner/account/AccountForm.tsx
  src/pages/@owner/account/constants/account-schema.ts
  src/pages/@owner/account/constants/bank.ts
  src/pages/@owner/account/hooks/useAccount.ts
  src/pages/@owner/account/mockup.ts
  src/pages/@owner/account/utils/format-account-number.ts
  src/pages/@owner/food-truck-onboarding/components/NameSection.tsx
  src/pages/@owner/message-list/@modal/(.)confirm-delete-modal/ConfirmExitModal.tsx
  src/pages/@owner/message-list/@modal/(.)delete-message-bottom-sheet/DeleteMessageBottomSheet.tsx
  src/pages/@owner/message-list/MessageList.tsx
  src/pages/@owner/message-list/components/Message.tsx
  src/pages/@owner/message-list/components/MessageForm.tsx
  src/pages/home/Home.tsx
  src/pages/set-location/SetLocation.tsx
  src/router/constant/routes.ts
  src/router/router.tsx
  src/shared/components/input/Input.stories.tsx
  src/shared/components/input/Input.tsx
  src/shared/styles/sharedStyles.css
Labels: ✨Feature, 🦊 동희

#95 [Feature/#83] edit profile pages
  src/pages/profile-setting/components/AgreementSection.tsx
  src/pages/profile-setting/components/ProfileImageSection.tsx
  src/pages/profile-setting/components/UserDataSection.tsx
  src/pages/set-user-info/SetUserInfo.tsx
  src/pages/set-user-info/components/SetUserEmail.tsx
  src/pages/set-user-info/components/SetUserGender.tsx
  src/pages/set-user-info/components/SetUserName.tsx
  src/pages/set-user-info/constant/mocks.ts
  src/pages/set-user-info/constant/set-user-constant.ts
  src/pages/set-user-info/types/set-user-types.ts
  src/router/constant/routes.ts
  src/router/router.tsx
Labels: ✨Feature, 🐯 동윤

#109 [Feat/#107] 일반유저 저장한 푸드트럭 페이지 layout 생성
  src/pages/save-food-truck-list/SaveFoodTruckList.tsx
  src/pages/save-food-truck-list/mockup.ts
  src/router/constant/routes.ts
  src/router/router.tsx
Labels: ✨Feature, 🦊 동희
