Repository CHA-CALL/ChaCall-FE, pull requests merged in 2025-10, with the labels that each got.

#114 [Feature/#112] 상세 내역 페이지
  apis/FoodTrucks.ts
  apis/Members.ts
  apis/Owners.ts
  apis/Reservations.ts
  apis/data-contracts.ts
  src/assets/svg/ic_sprite.svg
  src/pages/reservation-detail/ReservationDetail.tsx
  src/pages/reservation-detail/components/ReservationDetailRow.tsx
  src/pages/reservation-detail/components/ReservationDetailTopContent.tsx
  src/pages/reservation-detail/constant/reservation-detail.ts
  src/pages/reservation-detail/hooks/use-reservation-detail.ts
  src/router/constant/routes.ts
  src/router/router.tsx
  src/shared/components/icon/Icon.tsx
  src/shared/components/tooltip/Tooltip.tsx
Labels: ✨Feature, 🐯 동윤

#121 [Refactor/#120] api instance
  package.json
  pnpm-lock.yaml
  src/api/apiRequest.ts
  src/shared/components/custom-toast/CustomToast.tsx
  src/shared/hooks/use-role.ts
Labels: ✨Feature, 🦊 동희

#106 [Feature/#105] food truck card component
  src/assets/svg/ic_sprite.svg
  src/pages/reservation/Reservation.tsx
  src/pages/reservation/constant/mockUp.ts
  src/shared/components/food-truck-card/FoodTruckCard.stories.tsx
  src/shared/components/food-truck-card/FoodTruckCard.tsx
  src/shared/components/food-truck-card/components/CardButton.tsx
  src/shared/components/food-truck-card/components/CardImage.tsx
  src/shared/components/food-truck-card/components/FoodTruckClientCard.tsx
  src/shared/components/food-truck-card/components/FoodTruckProviderCard.tsx
  src/shared/components/food-truck-card/components/InfoRow.tsx
  src/shared/components/food-truck-card/components/ReservationClientCard.tsx
  src/shared/components/food-truck-card/components/ReservationProviderCard.tsx
  src/shared/components/food-truck-card/types/food-truck-card-types.ts
  src/shared/components/food-truck-card/utils/date-time-utils.ts
  src/shared/components/icon/Icon.stories.tsx
  src/shared/components/icon/Icon.tsx
  src/shared/constant/food-truck-card-variants.ts
  src/shared/constant/food-truck-category.ts
Labels: ✨Feature, 🐣 정현

#123 [Feature/#122] set location api
  apis/FoodTrucks.ts
  apis/Owners.ts
  apis/Test.ts
  apis/Users.ts
  apis/data-contracts.ts
  src/pages/set-location/SetLocation.tsx
  src/pages/set-location/api/index.ts
  src/pages/set-location/components/(.)section/(.)depths/Depth1Item.tsx
  src/pages/set-location/components/(.)section/(.)depths/Depth2Item.tsx
  src/pages/set-location/components/(.)section/(.)depths/Depth3Item.tsx
  src/pages/set-location/components/(.)section/(.)depths/DepthTitle.tsx
  src/pages/set-location/components/(.)section/(.)search/SearchResultItem.tsx
  src/pages/set-location/components/DepthSection.tsx
  src/pages/set-location/components/LocationCategoryLabels.tsx
  src/pages/set-location/components/SearchResultItem.tsx
  src/pages/set-location/components/SearchSection.tsx
  src/pages/set-location/components/SelectedChipsSheet.tsx
  src/pages/set-location/constant/location.ts
  src/pages/set-location/constant/mocks.ts
  src/pages/set-location/hooks/use-depths.ts
  src/pages/set-location/hooks/use-location.ts
  src/pages/set-location/hooks/use-locations.ts
  src/pages/set-location/hooks/use-region-search.ts
  src/pages/set-location/hooks/use-regions.ts
  src/shared/components/loading/Loading.tsx
  src/shared/querykey/regions.ts
  src/shared/store/regions-store.ts
Labels: ✨Feature, 🦊 동희

#102 [Feature/#97] menu register page
  src/pages/@owner/menu/MenuList.tsx
  src/pages/@owner/menu/MenuRegister.tsx
  src/pages/@owner/menu/components/MenuInput.tsx
  src/pages/@owner/menu/components/MenuItem.tsx
  src/pages/@owner/menu/components/ToggleSwitch.tsx
  src/pages/@owner/menu/constant/menu-list-sort.ts
  src/pages/@owner/menu/constant/menu.ts
  src/pages/@owner/menu/constant/mockUp.ts
  src/pages/@owner/menu/hooks/use-menu-form.ts
  src/pages/@owner/message-list/components/MessageForm.tsx
  src/router/constant/routes.ts
  src/router/router.tsx
  src/shared/components/button-floating/ButtonFloating.tsx
  src/shared/components/text-area/Textarea.stories.tsx
  src/shared/components/text-area/Textarea.tsx
Labels: ✨Feature, 🐣 정현
